<?php

namespace App\Admin\Controllers;

use Encore\Admin\Controllers\AuthController as BaseAuthController;
use Illuminate\Http\Request;


class AuthController extends BaseAuthController
{

    public function postLogin ( Request $request )
    {
        $request['remember'] = 0;
        return parent ::postLogin ( $request ); // TODO: Change the autogenerated stub
    }

}
