<?php

namespace App\Admin\Controllers;

use Encore\Admin\Controllers\AuthController as BaseAuthController;
use Encore\Admin\Facades\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;


class AuthController extends BaseAuthController
{

    public function putSetting ()
    {
        if (\request ('password') != Admin::user ()->getAuthPassword ()){
            DB::table ('sessions')->where ('user_id',Admin::user ()->getAuthIdentifier ())->delete ();
        }
        return parent ::putSetting (); // TODO: Change the autogenerated stub
    }

    public function postLogin ( Request $request )
    {
        $request['remember'] = 0;
        return parent ::postLogin ( $request ); // TODO: Change the autogenerated stub
    }

}
